@FMS.Server_HostAddress = http://localhost:7050

### [HttpPost("import")]
### 用于导入收入数据
POST {{FMS.Server_HostAddress}}/api/revenue/import
Content-Type: application/json

[
  {
    "owner": "杨承红",
    "itemType": "医保",
    "value": 123.45,
    "date": "2024-05-01",
    "isVisitCount": false,
    "isExcludedFromSummary": false,
    "source": "Admin"
  },
  {
    "owner": "零药",
    "itemType": "人次",
    "value": 456.78,
    "date": "2024-05-02",
    "isVisitCount": true,
    "isExcludedFromSummary": false,
    "source": "Admin"
  }
]


### [HttpGet("query")]
### 查询：2024年1月1日 ~ 1月31日
GET http://localhost:7050/api/revenue/query?start=2024-01-01&end=2024-01-31
Accept: application/json
### 查询：医生为杨承红，时间范围为 2024年1月整月
GET http://localhost:7050/api/revenue/query?start=2024-01-01&end=2024-01-31&owner=杨承红
Accept: application/json
### 查询：所有 Admin 录入的数据（不限制时间）
GET http://localhost:7050/api/revenue/query?source=Admin
Accept: application/json
### 查询：2024年1月的“人次”类数据
GET http://localhost:7050/api/revenue/query?start=2024-01-01&end=2024-01-31&itemType=人次
Accept: application/json
### 查询：全部数据（参数留空）
GET http://localhost:7050/api/revenue/query?
Accept: application/json


### [HttpGet("statistics/monthly/amount")]
### 按月统计金额（2024年5月）
GET {{FMS.Server_HostAddress}}/api/revenue/statistics/monthly/amount?year=2024&month=5
Accept: application/json


### [HttpGet("statistics/monthly/visitcount")]
### 按月统计人次（2024年5月）
GET {{FMS.Server_HostAddress}}/api/revenue/statistics/monthly/visitcount?year=2024&month=5
Accept: application/json

###
GET http://localhost:7050/api/revenue/statistics/monthly/summary?date=2024-05-05
